/* Auto-generated by tools/generate_css_colors.py - do not edit. */
/* Shortest keyword<->hash form for every CSS Color 4 named color. */

#ifndef TURBOHTML_CSS_COLORS_H
#define TURBOHTML_CSS_COLORS_H

#include <stdint.h>

typedef struct {
    const char *key;
    uint8_t key_len;
    const char *val;
    uint8_t val_len;
} th_css_color_entry;

/* keyword -> shortest hash, sorted by keyword for a first-byte bucketed scan. */
static const int th_css_name_count = 105;
static const th_css_color_entry th_css_name_to_hex[] = {
    {"aliceblue", 9u, "#f0f8ff", 7u},
    {"antiquewhite", 12u, "#faebd7", 7u},
    {"aquamarine", 10u, "#7fffd4", 7u},
    {"black", 5u, "#000", 4u},
    {"blanchedalmond", 14u, "#ffebcd", 7u},
    {"blueviolet", 10u, "#8a2be2", 7u},
    {"burlywood", 9u, "#deb887", 7u},
    {"cadetblue", 9u, "#5f9ea0", 7u},
    {"chartreuse", 10u, "#7fff00", 7u},
    {"chocolate", 9u, "#d2691e", 7u},
    {"cornflowerblue", 14u, "#6495ed", 7u},
    {"cornsilk", 8u, "#fff8dc", 7u},
    {"darkblue", 8u, "#00008b", 7u},
    {"darkcyan", 8u, "#008b8b", 7u},
    {"darkgoldenrod", 13u, "#b8860b", 7u},
    {"darkgray", 8u, "#a9a9a9", 7u},
    {"darkgreen", 9u, "#006400", 7u},
    {"darkgrey", 8u, "#a9a9a9", 7u},
    {"darkkhaki", 9u, "#bdb76b", 7u},
    {"darkmagenta", 11u, "#8b008b", 7u},
    {"darkolivegreen", 14u, "#556b2f", 7u},
    {"darkorange", 10u, "#ff8c00", 7u},
    {"darkorchid", 10u, "#9932cc", 7u},
    {"darksalmon", 10u, "#e9967a", 7u},
    {"darkseagreen", 12u, "#8fbc8f", 7u},
    {"darkslateblue", 13u, "#483d8b", 7u},
    {"darkslategray", 13u, "#2f4f4f", 7u},
    {"darkslategrey", 13u, "#2f4f4f", 7u},
    {"darkturquoise", 13u, "#00ced1", 7u},
    {"darkviolet", 10u, "#9400d3", 7u},
    {"deeppink", 8u, "#ff1493", 7u},
    {"deepskyblue", 11u, "#00bfff", 7u},
    {"dodgerblue", 10u, "#1e90ff", 7u},
    {"firebrick", 9u, "#b22222", 7u},
    {"floralwhite", 11u, "#fffaf0", 7u},
    {"forestgreen", 11u, "#228b22", 7u},
    {"fuchsia", 7u, "#f0f", 4u},
    {"gainsboro", 9u, "#dcdcdc", 7u},
    {"ghostwhite", 10u, "#f8f8ff", 7u},
    {"goldenrod", 9u, "#daa520", 7u},
    {"greenyellow", 11u, "#adff2f", 7u},
    {"honeydew", 8u, "#f0fff0", 7u},
    {"indianred", 9u, "#cd5c5c", 7u},
    {"lavender", 8u, "#e6e6fa", 7u},
    {"lavenderblush", 13u, "#fff0f5", 7u},
    {"lawngreen", 9u, "#7cfc00", 7u},
    {"lemonchiffon", 12u, "#fffacd", 7u},
    {"lightblue", 9u, "#add8e6", 7u},
    {"lightcoral", 10u, "#f08080", 7u},
    {"lightcyan", 9u, "#e0ffff", 7u},
    {"lightgoldenrodyellow", 20u, "#fafad2", 7u},
    {"lightgray", 9u, "#d3d3d3", 7u},
    {"lightgreen", 10u, "#90ee90", 7u},
    {"lightgrey", 9u, "#d3d3d3", 7u},
    {"lightpink", 9u, "#ffb6c1", 7u},
    {"lightsalmon", 11u, "#ffa07a", 7u},
    {"lightseagreen", 13u, "#20b2aa", 7u},
    {"lightskyblue", 12u, "#87cefa", 7u},
    {"lightslategray", 14u, "#789", 4u},
    {"lightslategrey", 14u, "#789", 4u},
    {"lightsteelblue", 14u, "#b0c4de", 7u},
    {"lightyellow", 11u, "#ffffe0", 7u},
    {"limegreen", 9u, "#32cd32", 7u},
    {"magenta", 7u, "#f0f", 4u},
    {"mediumaquamarine", 16u, "#66cdaa", 7u},
    {"mediumblue", 10u, "#0000cd", 7u},
    {"mediumorchid", 12u, "#ba55d3", 7u},
    {"mediumpurple", 12u, "#9370db", 7u},
    {"mediumseagreen", 14u, "#3cb371", 7u},
    {"mediumslateblue", 15u, "#7b68ee", 7u},
    {"mediumspringgreen", 17u, "#00fa9a", 7u},
    {"mediumturquoise", 15u, "#48d1cc", 7u},
    {"mediumvioletred", 15u, "#c71585", 7u},
    {"midnightblue", 12u, "#191970", 7u},
    {"mintcream", 9u, "#f5fffa", 7u},
    {"mistyrose", 9u, "#ffe4e1", 7u},
    {"moccasin", 8u, "#ffe4b5", 7u},
    {"navajowhite", 11u, "#ffdead", 7u},
    {"olivedrab", 9u, "#6b8e23", 7u},
    {"orangered", 9u, "#ff4500", 7u},
    {"palegoldenrod", 13u, "#eee8aa", 7u},
    {"palegreen", 9u, "#98fb98", 7u},
    {"paleturquoise", 13u, "#afeeee", 7u},
    {"palevioletred", 13u, "#db7093", 7u},
    {"papayawhip", 10u, "#ffefd5", 7u},
    {"peachpuff", 9u, "#ffdab9", 7u},
    {"powderblue", 10u, "#b0e0e6", 7u},
    {"rebeccapurple", 13u, "#639", 4u},
    {"rosybrown", 9u, "#bc8f8f", 7u},
    {"royalblue", 9u, "#4169e1", 7u},
    {"saddlebrown", 11u, "#8b4513", 7u},
    {"sandybrown", 10u, "#f4a460", 7u},
    {"seagreen", 8u, "#2e8b57", 7u},
    {"seashell", 8u, "#fff5ee", 7u},
    {"slateblue", 9u, "#6a5acd", 7u},
    {"slategray", 9u, "#708090", 7u},
    {"slategrey", 9u, "#708090", 7u},
    {"springgreen", 11u, "#00ff7f", 7u},
    {"steelblue", 9u, "#4682b4", 7u},
    {"transparent", 11u, "#0000", 5u},
    {"turquoise", 9u, "#40e0d0", 7u},
    {"white", 5u, "#fff", 4u},
    {"whitesmoke", 10u, "#f5f5f5", 7u},
    {"yellow", 6u, "#ff0", 4u},
    {"yellowgreen", 11u, "#9acd32", 7u},
};

/* th_css_name_first[c] is the first table index whose keyword starts with a byte >= c, so the keywords
   beginning with byte c are [th_css_name_first[c], th_css_name_first[c + 1]). */
static const uint16_t th_css_name_first[257] = {
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,   7,   12,  33,  33,  37,  41,  42,  43,  43,  43,  63,
    77,  78,  80,  87,  87,  90,  99,  101, 101, 101, 103, 103, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105,
    105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105,
    105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105,
    105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105,
    105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105,
    105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105,
    105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105};

/* hash -> shortest keyword, sorted by hash string for a binary search (every hash shares the '#' byte). */
static const int th_css_hex_count = 32;
static const th_css_color_entry th_css_hex_to_name[] = {
    {"#000080", 7u, "navy", 4u},   {"#008000", 7u, "green", 5u},  {"#008080", 7u, "teal", 4u},
    {"#4b0082", 7u, "indigo", 6u}, {"#800000", 7u, "maroon", 6u}, {"#800080", 7u, "purple", 6u},
    {"#808000", 7u, "olive", 5u},  {"#808080", 7u, "gray", 4u},   {"#a0522d", 7u, "sienna", 6u},
    {"#a52a2a", 7u, "brown", 5u},  {"#c0c0c0", 7u, "silver", 6u}, {"#cd853f", 7u, "peru", 4u},
    {"#d2b48c", 7u, "tan", 3u},    {"#da70d6", 7u, "orchid", 6u}, {"#dda0dd", 7u, "plum", 4u},
    {"#ee82ee", 7u, "violet", 6u}, {"#f00", 4u, "red", 3u},       {"#f0e68c", 7u, "khaki", 5u},
    {"#f0ffff", 7u, "azure", 5u},  {"#f5deb3", 7u, "wheat", 5u},  {"#f5f5dc", 7u, "beige", 5u},
    {"#fa8072", 7u, "salmon", 6u}, {"#faf0e6", 7u, "linen", 5u},  {"#ff0000", 7u, "red", 3u},
    {"#ff6347", 7u, "tomato", 6u}, {"#ff7f50", 7u, "coral", 5u},  {"#ffa500", 7u, "orange", 6u},
    {"#ffc0cb", 7u, "pink", 4u},   {"#ffd700", 7u, "gold", 4u},   {"#ffe4c4", 7u, "bisque", 6u},
    {"#fffafa", 7u, "snow", 4u},   {"#fffff0", 7u, "ivory", 5u},
};

#endif /* TURBOHTML_CSS_COLORS_H */
