# Subsystem: dom (_c/dom) — the node model, parsing entrypoints, and tree reconstruction.
from collections.abc import Callable, Iterable, Iterator, Mapping, MutableMapping, Sequence
from enum import Enum, IntEnum
from re import Pattern
from typing import TypeAlias, final

from turbohtml._article import Article as Article
from turbohtml._feed import Feed
from turbohtml._links import Link
from turbohtml._locations import SourceLocation
from turbohtml._render import Canonical, Html, Markdown, PlainText
from turbohtml._structured_data import JSONValue, MicrodataItem, OpenGraph, RdfaItem, StructuredData
from turbohtml.mutations import MutationRecord

_Filter: TypeAlias = str | Pattern[str] | bool | Callable[[str | None], bool] | list[_Filter]

class Axis(IntEnum):
    DESCENDANTS = 0
    CHILDREN = 1
    ANCESTORS = 2
    NEXT_SIBLINGS = 3
    PREVIOUS_SIBLINGS = 4
    FOLLOWING = 5
    PRECEDING = 6

class Namespace(Enum):
    HTML = "html"
    SVG = "svg"
    MATHML = "math"

class Node:
    @property
    def parent(self) -> Element | Document | None: ...
    @property
    def children(self) -> Sequence[Node]: ...
    @property
    def next_sibling(self) -> Node | None: ...
    @property
    def previous_sibling(self) -> Node | None: ...
    @property
    def descendants(self) -> Iterator[Node]: ...
    @property
    def ancestors(self) -> Iterator[Element | Document]: ...
    @property
    def next_siblings(self) -> Iterator[Node]: ...
    @property
    def previous_siblings(self) -> Iterator[Node]: ...
    @property
    def following(self) -> Iterator[Node]: ...
    @property
    def preceding(self) -> Iterator[Node]: ...
    @property
    def strings(self) -> Iterator[str]: ...
    @property
    def stripped_strings(self) -> Iterator[str]: ...
    @property
    def text(self) -> str: ...
    @property
    def html(self) -> str: ...
    @property
    def inner_html(self) -> str: ...
    @property
    def source_line(self) -> int | None: ...
    @property
    def source_col(self) -> int | None: ...
    @property
    def position(self) -> tuple[int, int] | None: ...
    @property
    def source_location(self) -> SourceLocation | None: ...
    @property
    def assigned_slot(self) -> Element | None: ...
    @property
    def flattened_children(self) -> list[Node]: ...
    def find(
        self,
        tag: _Filter | None = None,
        /,
        *,
        axis: Axis = ...,
        attrs: Mapping[str, _Filter] | None = ...,
        class_: _Filter | None = ...,
        text: _Filter | None = ...,
        **filters: _Filter,
    ) -> Element | None: ...
    def find_all(
        self,
        tag: _Filter | None = None,
        /,
        *,
        axis: Axis = ...,
        attrs: Mapping[str, _Filter] | None = ...,
        class_: _Filter | None = ...,
        text: _Filter | None = ...,
        limit: int | None = ...,
        **filters: _Filter,
    ) -> list[Element]: ...
    def select(self, selector: str, /) -> list[Element]: ...
    def select_one(self, selector: str, /) -> Element | None: ...
    def xpath(
        self,
        expression: str,
        /,
        *,
        namespaces: dict[str, str] | None = ...,
        smart_strings: bool = ...,
        extensions: dict[tuple[str | None, str], Callable[..., str | float | bool | Element | Iterable[Element]]]
        | None = ...,
        **variables: str | float | bool | Element | Iterable[Element],
    ) -> list[Element | str]: ...
    def xpath_iter(
        self,
        expression: str,
        /,
        *,
        namespaces: dict[str, str] | None = ...,
        smart_strings: bool = ...,
        extensions: dict[tuple[str | None, str], Callable[..., str | float | bool | Element | Iterable[Element]]]
        | None = ...,
        **variables: str | float | bool | Element | Iterable[Element],
    ) -> Iterator[Element | str]: ...
    def xpath_one(
        self,
        expression: str,
        /,
        *,
        namespaces: dict[str, str] | None = ...,
        smart_strings: bool = ...,
        extensions: dict[tuple[str | None, str], Callable[..., str | float | bool | Element | Iterable[Element]]]
        | None = ...,
        **variables: str | float | bool | Element | Iterable[Element],
    ) -> Element | str | None: ...
    def equals(self, other: Node, /) -> bool: ...
    def matches(self, selector: str, /) -> bool: ...
    def closest(self, selector: str, /) -> Element | None: ...
    def prune(self, selector: str, /) -> Node: ...
    def remove(self, selector: str, /) -> Node: ...
    def strip_tags(self, selector: str, /) -> Node: ...
    def re(self, pattern: str | Pattern[str], /, *, attr: str | None = None) -> list[str]: ...
    def re_first(
        self, pattern: str | Pattern[str], /, default: str | None = None, *, attr: str | None = None
    ) -> str | None: ...
    def serialize(self, options: Html | None = None) -> str: ...
    def serialize_iter(self, options: Html | None = None) -> Iterator[str]: ...
    def encode(self, encoding: str = "utf-8", options: Html | None = None) -> bytes: ...
    def canonicalize(self, options: Canonical | None = None) -> bytes: ...
    def to_source(self) -> str: ...
    def to_markdown(self, options: Markdown | None = None) -> str: ...
    def to_text(self, options: PlainText | None = None) -> str: ...
    def to_annotated_text(
        self, annotation_rules: Mapping[str, Sequence[str]], options: PlainText | None = None
    ) -> tuple[str, list[tuple[int, int, str]]]: ...
    def links(self) -> list[Link]: ...
    def rewrite_links(self, replace: Callable[[str], str | None], /) -> None: ...
    def resolve_links(self, base_url: str, /) -> None: ...
    def main_content(self) -> Element | None: ...
    def main_text(self) -> str: ...
    def tables(self) -> list[list[list[str]]]: ...
    def article(self) -> Article: ...
    def insert_before(self, *nodes: Node) -> None: ...
    def insert_after(self, *nodes: Node) -> None: ...
    def replace_with(self, *nodes: Node) -> None: ...
    def wrap(self, wrapper: Element, /) -> Element: ...
    def wrap_siblings(self, wrapper: Element, /, *, until: Node | None = None) -> Element: ...
    def unwrap(self) -> Node: ...
    def extract(self) -> Node: ...
    def decompose(self) -> None: ...
    def __iter__(self) -> Iterator[Node]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Node: ...
    def __bool__(self) -> bool: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

@final
class Element(Node):
    __match_args__ = ("tag",)
    def __init__(
        self,
        tag: str,
        attrs: Mapping[str, str | list[str] | None] | None = None,
        children: Iterable[Node] | None = None,
    ) -> None: ...
    @property
    def tag(self) -> str: ...
    @property
    def namespace(self) -> Namespace: ...
    @property
    def attrs(self) -> MutableMapping[str, str | list[str] | None]: ...
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
    @property
    def field_value(self) -> str | list[str] | None: ...
    @field_value.setter
    def field_value(self, value: str | list[str] | None) -> None: ...
    @property
    def checked(self) -> bool: ...
    @checked.setter
    def checked(self, value: bool) -> None: ...
    @property
    def shadow_root(self) -> ShadowRoot | None: ...
    def attach_shadow(self, mode: str = "open") -> ShadowRoot: ...
    def assigned_nodes(self, *, flatten: bool = False) -> list[Node]: ...
    def assigned_elements(self, *, flatten: bool = False) -> list[Element]: ...
    def form_data(self) -> list[tuple[str, str]]: ...
    def rows(self) -> list[list[str]]: ...
    def records(self) -> list[dict[str, str]]: ...
    def css_path(self) -> str: ...
    def xpath_path(self) -> str: ...
    def attr(self, name: str, /, default: str | None = None) -> str | None: ...
    def append(self, child: Node, /) -> None: ...
    def extend(self, children: Iterable[Node], /) -> None: ...
    def insert(self, index: int, child: Node, /) -> None: ...
    def clear(self) -> None: ...
    def normalize(self) -> None: ...
    def wrap_children(self, wrapper: Element, /) -> Element: ...
    def has_class(self, name: str, /) -> bool: ...
    def add_class(self, name: str, /) -> Element: ...
    def remove_class(self, name: str, /) -> Element: ...
    def toggle_class(self, name: str, /) -> Element: ...
    def set_inner_html(self, html: str, /) -> None: ...
    def set_text(self, text: str, /) -> None: ...
    def insert_adjacent_html(self, position: str, html: str, /) -> None: ...

@final
class Text(Node):
    __match_args__ = ("data",)
    def __init__(self, data: str) -> None: ...
    @property
    def data(self) -> str: ...
    @data.setter
    def data(self, value: str) -> None: ...

@final
class Comment(Node):
    __match_args__ = ("data",)
    def __init__(self, data: str) -> None: ...
    @property
    def data(self) -> str: ...
    @data.setter
    def data(self, value: str) -> None: ...

@final
class CData(Node):
    __match_args__ = ("data",)
    def __init__(self, data: str) -> None: ...
    @property
    def data(self) -> str: ...
    @data.setter
    def data(self, value: str) -> None: ...

@final
class ProcessingInstruction(Node):
    __match_args__ = ("target", "data")
    def __init__(self, target: str, data: str) -> None: ...
    @property
    def target(self) -> str: ...
    @property
    def data(self) -> str: ...

@final
class Doctype(Node):
    __match_args__ = ("name",)
    @property
    def name(self) -> str: ...
    @property
    def public_id(self) -> str | None: ...
    @property
    def system_id(self) -> str | None: ...

@final
class TreeWalker:
    def __init__(
        self,
        root: Node,
        what_to_show: int = ...,
        filter: Callable[[Node], int] | None = ...,  # noqa: A002  # the DOM constructor's argument name
    ) -> None: ...
    @property
    def root(self) -> Node: ...
    @property
    def what_to_show(self) -> int: ...
    @property
    def filter(self) -> Callable[[Node], int] | None: ...
    @property
    def current_node(self) -> Node: ...
    @current_node.setter
    def current_node(self, value: Node) -> None: ...
    def parent_node(self) -> Node | None: ...
    def first_child(self) -> Node | None: ...
    def last_child(self) -> Node | None: ...
    def next_sibling(self) -> Node | None: ...
    def previous_sibling(self) -> Node | None: ...
    def next_node(self) -> Node | None: ...
    def previous_node(self) -> Node | None: ...

@final
class NodeIterator:
    def __init__(
        self,
        root: Node,
        what_to_show: int = ...,
        filter: Callable[[Node], int] | None = ...,  # noqa: A002  # the DOM constructor's argument name
    ) -> None: ...
    @property
    def root(self) -> Node: ...
    @property
    def what_to_show(self) -> int: ...
    @property
    def filter(self) -> Callable[[Node], int] | None: ...
    @property
    def reference_node(self) -> Node: ...
    @property
    def pointer_before_reference_node(self) -> bool: ...
    def next_node(self) -> Node | None: ...
    def previous_node(self) -> Node | None: ...
    def __iter__(self) -> NodeIterator: ...
    def __next__(self) -> Node: ...

@final
class ParseError:
    @property
    def code(self) -> str: ...
    @property
    def line(self) -> int: ...
    @property
    def col(self) -> int: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class HTMLParseError(Exception):
    error: ParseError

@final
class Document(Node):
    __match_args__ = ("root",)
    @property
    def root(self) -> Element | None: ...
    @property
    def encoding(self) -> str | None: ...
    def base_url(self, fallback: str = "") -> str: ...
    def meta_refresh(self, fallback: str = "") -> tuple[float, str] | None: ...
    def structured_data(self, base_url: str | None = None) -> StructuredData: ...
    def json_ld(self) -> list[JSONValue]: ...
    def opengraph(self, base_url: str | None = None) -> OpenGraph: ...
    def microdata(self, base_url: str | None = None) -> list[MicrodataItem]: ...
    def rdfa(self, base_url: str | None = None) -> list[RdfaItem]: ...
    def dublin_core(self) -> dict[str, str]: ...
    def feed(self) -> Feed | None: ...
    @property
    def errors(self) -> list[ParseError]: ...

@final
class ShadowRoot(Node):
    __match_args__ = ("mode",)
    @property
    def mode(self) -> str: ...
    @property
    def host(self) -> Element: ...
    @property
    def delegates_focus(self) -> bool: ...
    @property
    def clonable(self) -> bool: ...
    def append(self, child: Node, /) -> None: ...
    def set_inner_html(self, html: str, /) -> None: ...

@final
class IncrementalParser:
    def __init__(self, *, encoding: str = "utf-8", positions: bool = True, source_locations: bool = False) -> None: ...
    def feed(self, data: str | bytes) -> None: ...
    def close(self) -> Document: ...
    def __enter__(self) -> IncrementalParser: ...
    def __exit__(self, *exc: object) -> None: ...

@final
class Range:
    START_TO_START: int
    START_TO_END: int
    END_TO_END: int
    END_TO_START: int
    def __init__(self, container: Node, offset: int = 0) -> None: ...
    @property
    def start_container(self) -> Node: ...
    @property
    def start_offset(self) -> int: ...
    @property
    def end_container(self) -> Node: ...
    @property
    def end_offset(self) -> int: ...
    @property
    def collapsed(self) -> bool: ...
    @property
    def common_ancestor_container(self) -> Node: ...
    def set_start(self, container: Node, offset: int, /) -> None: ...
    def set_end(self, container: Node, offset: int, /) -> None: ...
    def set_start_before(self, node: Node, /) -> None: ...
    def set_start_after(self, node: Node, /) -> None: ...
    def set_end_before(self, node: Node, /) -> None: ...
    def set_end_after(self, node: Node, /) -> None: ...
    def select_node(self, node: Node, /) -> None: ...
    def select_node_contents(self, node: Node, /) -> None: ...
    def collapse(self, to_start: bool = False, /) -> None: ...
    def compare_boundary_points(self, how: int, source_range: Range, /) -> int: ...
    def compare_point(self, node: Node, offset: int, /) -> int: ...
    def is_point_in_range(self, node: Node, offset: int, /) -> bool: ...
    def intersects_node(self, node: Node, /) -> bool: ...
    def clone_contents(self) -> Node: ...
    def extract_contents(self) -> Node: ...
    def delete_contents(self) -> None: ...
    def insert_node(self, node: Node, /) -> None: ...
    def surround_contents(self, new_parent: Node, /) -> Node: ...
    def clone_range(self) -> Range: ...

@final
class StaticRange:
    def __init__(self, start_container: Node, start_offset: int, end_container: Node, end_offset: int) -> None: ...
    @property
    def start_container(self) -> Node: ...
    @property
    def start_offset(self) -> int: ...
    @property
    def end_container(self) -> Node: ...
    @property
    def end_offset(self) -> int: ...
    @property
    def collapsed(self) -> bool: ...

class MutationObserver:
    def __init__(self, callback: Callable[[list[MutationRecord], MutationObserver], object] | None = None) -> None: ...
    def observe(
        self,
        target: Node,
        *,
        child_list: bool = False,
        attributes: bool = False,
        character_data: bool = False,
        subtree: bool = False,
        attribute_old_value: bool = False,
        character_data_old_value: bool = False,
        attribute_filter: Sequence[str] | None = None,
    ) -> None: ...
    def take_records(self) -> list[MutationRecord]: ...
    def deliver(self) -> list[MutationRecord]: ...
    def disconnect(self) -> None: ...

def _register_mutation_record(record_type: type, /) -> None: ...
def parse(
    markup: str | bytes,
    *,
    encoding: str | None = None,
    strict: bool = False,
    detect_encoding: bool = False,
    positions: bool = True,
    source_locations: bool = False,
    scripting: bool = False,
    allow_declarative_shadow_roots: bool = True,
) -> Document: ...
def parse_xml(markup: str) -> Document: ...
def parse_fragment(
    html: str,
    context: str = "div",
    *,
    positions: bool = True,
    source_locations: bool = False,
    scripting: bool = False,
    allow_declarative_shadow_roots: bool = False,
) -> Element: ...
def _build_document(
    head: list[Node],
    body: list[Node],
    title: str | None = None,
    lang: str | None = None,
    charset: str | None = None,
) -> Document: ...
def _detect(data: bytes, /) -> tuple[str | None, bool, list[tuple[str, int]], bool]: ...
def _detect_language(
    text: str, allowed: frozenset[str] | None, excluded: frozenset[str], /
) -> tuple[str | None, float, str | None, str | None]: ...
def _normalize(form: int, text: str, /) -> str: ...
def _is_normalized(form: int, text: str, /) -> bool: ...
def _parse_tree(html: str, scripting: bool = ..., /) -> str: ...
def _parse_fragment(html: str, context: str, scripting: bool = ..., /) -> str: ...
def _parse_only(html: str, /) -> None: ...
def _parse_into(html: str, builder: object, /) -> object: ...
def _reconstruct(kind: int, descriptor: tuple[object, ...], children: list[Node], /) -> Node: ...
