# Subsystem: query (_c/query) — XPath compilation hooks, smart-string registration, and the compiled expression object.
from collections.abc import Callable
from pathlib import Path
from typing import final

from .dom import Element, Node

def _xpath_parse(expression: str, /) -> str: ...
def _matches_many(nodes: list[Element], selector: str, /) -> list[Element]: ...
def _select_many(roots: list[Element], selector: str, /) -> list[Element]: ...
def _xslt_resolve_imports(
    stylesheet: Node, base_url: str | None, loader: Callable[[str | Path, str], tuple[Node, Path, Path]], /
) -> list[Node] | None: ...
def _xslt_transform(
    stylesheet: Node, source: Node, params: dict[str, str] | None = ..., imports: list[Node] | None = ..., /
) -> str: ...
def _css_to_xpath(selector: str, prefix: str, /) -> str: ...
def _css_specificity(selector: str, /) -> list[tuple[int, int, int]]: ...
def _css_parse_declarations(text: str, /) -> tuple[tuple[str, str, bool], ...]: ...
def _css_parse_rules(text: str, /) -> tuple[tuple[str, tuple[tuple[str, str, bool], ...]], ...]: ...
def _css_computed_style(element: Element, /) -> tuple[tuple[str, str], ...]: ...
def _register_xpath_string(xpath_string_type: type, /) -> None: ...
def _register_selector_error(selector_error_type: type[ValueError], /) -> None: ...

@final
class XPath:
    def __init__(
        self,
        expression: str,
        /,
        *,
        smart_strings: bool = ...,
        extensions: dict[tuple[str | None, str], Callable[..., str | float | bool]] | None = ...,
    ) -> None: ...
    def __call__(self, node: Node, /, **variables: str | float | bool) -> list[Element | str]: ...
    @property
    def path(self) -> str: ...
