# Subsystem: query (_c/query) — XPath compilation hooks, smart-string registration, and the compiled expression object.
from collections.abc import Callable, Iterable
from pathlib import Path
from typing import final

from .dom import Element, Node

def _xpath_parse(expression: str, /) -> str: ...
def _matches_many(nodes: list[Element], selector: str, /) -> list[Element]: ...
def _select_many(roots: list[Element], selector: str, /) -> list[Element]: ...
def _query_unique(elements: Iterable[Element], /) -> list[Element]: ...
def _query_siblings(nodes: list[Element], /) -> list[Element]: ...
def _query_text(nodes: list[Element], /) -> str: ...
def _query_attr(nodes: list[Element], name: str, /) -> str | None: ...
def _query_has_class(nodes: list[Element], name: str, /) -> bool: ...
def _query_add_class(nodes: list[Element], name: str, /) -> None: ...
def _query_remove_class(nodes: list[Element], name: str, /) -> None: ...
def _query_toggle_class(nodes: list[Element], name: str, /) -> None: ...
def _xslt_resolve_imports(
    stylesheet: Node,
    base_url: str | None = ...,
    allow_imports: bool = ...,
    import_root: str | Path | None = ...,
    /,
) -> list[Node] | None: ...
def _xslt_compile(stylesheet: Node, imports: list[Node] | None = ..., /) -> object: ...
def _xslt_transform(compiled: object, source: Node, params: dict[str, str] | None = ..., /) -> str: ...
def _css_to_xpath(selector: str, prefix: str, /) -> str: ...
def _css_specificity(selector: str, /) -> list[tuple[int, int, int]]: ...
def _css_parse_declarations(text: str, /) -> tuple[tuple[str, str, bool], ...]: ...
def _css_declaration_index(items: tuple[tuple[str, str, bool], ...], /) -> dict[str, int]: ...
def _css_declaration_text(items: tuple[tuple[str, str, bool], ...], /) -> str: ...
def _css_parse_rules(text: str, /) -> tuple[tuple[str, tuple[tuple[str, str, bool], ...]], ...]: ...
def _css_computed_style(element: Element, /) -> tuple[tuple[str, str], ...]: ...
def _css_escape_identifier(ident: str, /) -> str: ...
def _register_xpath_string(xpath_string_type: type, /) -> None: ...
def _register_selector_error(selector_error_type: type[ValueError], /) -> None: ...

@final
class XPath:
    def __init__(
        self,
        expression: str,
        /,
        *,
        smart_strings: bool = ...,
        extensions: dict[tuple[str | None, str], Callable[..., str | float | bool]] | None = ...,
    ) -> None: ...
    def __call__(self, node: Node, /, **variables: str | float | bool) -> list[Element | str]: ...
    @property
    def path(self) -> str: ...
