# Subsystem: serialize (_c/serialize) — output formatting, escaping, and markup-safe helpers.
from enum import Enum
from typing import final

from turbohtml._minify import JSMinify

class Formatter(Enum):
    WHATWG = "whatwg"
    MINIMAL = "minimal"
    NAMED_ENTITIES = "named"

@final
class Indent:
    def __init__(self, indent: int | str = 2) -> None: ...
    @property
    def unit(self) -> str: ...

@final
class Minify:
    def __init__(
        self,
        *,
        collapse_whitespace: bool = ...,
        omit_optional_tags: bool = ...,
        unquote_attributes: bool = ...,
        strip_comments: bool = ...,
        minify_js: JSMinify | None = ...,
        minify_css: bool = ...,
    ) -> None: ...
    @property
    def collapse_whitespace(self) -> bool: ...
    @property
    def omit_optional_tags(self) -> bool: ...
    @property
    def unquote_attributes(self) -> bool: ...
    @property
    def strip_comments(self) -> bool: ...
    @property
    def minify_js(self) -> JSMinify | None: ...
    @property
    def minify_css(self) -> bool: ...

def escape(s: str, quote: bool = ...) -> str: ...
def unescape(s: str, /) -> str: ...
def _minify_css(css: str, baseline: int, /) -> str: ...
def _minify_css_inline(css: str, baseline: int, /) -> str: ...
def _minify_js(source: str, fold: bool, mangle: bool, /) -> str: ...
def _register_js_minify(js_minify_type: type[JSMinify], /) -> None: ...
def _register_render_configs(markdown_type: type, plaintext_type: type, html_type: type, /) -> None: ...
def _minify_js_tokens(source: str, /) -> str: ...
def _minify_js_parse(source: str, /) -> str: ...
def _markup_escape(s: object, /) -> str: ...
def _markup_escape_silent(s: object, /) -> str: ...
def _markup_soft_str(s: object, /) -> str: ...
