# Subsystem: tokenizer (_c/tokenizer) — the HTML tokenization surface.
from collections.abc import Iterator
from enum import IntEnum
from typing import final

class TokenType(IntEnum):
    TEXT = 0
    START_TAG = 1
    END_TAG = 2
    COMMENT = 3
    DOCTYPE = 4
    CHARACTER_REFERENCE = 5

@final
class Token:
    @property
    def type(self) -> TokenType: ...
    @property
    def data(self) -> str | None: ...
    @property
    def source(self) -> str | None: ...
    @property
    def tag(self) -> str | None: ...
    @property
    def attrs(self) -> list[tuple[str, str]] | None: ...
    @property
    def self_closing(self) -> bool: ...
    @property
    def name(self) -> str | None: ...
    @property
    def public_id(self) -> str | None: ...
    @property
    def system_id(self) -> str | None: ...
    @property
    def force_quirks(self) -> bool: ...
    @property
    def line(self) -> int: ...
    @property
    def col(self) -> int: ...
    def attr(self, name: str, default: str | None = None) -> str | None: ...

@final
class Tokenizer:
    def __init__(
        self, *, resolve_references: bool = ..., capture_source: bool = ..., capture_attributes: bool = ...
    ) -> None: ...
    def feed(self, data: str) -> Iterator[Token]: ...
    def close(self) -> Iterator[Token]: ...
    def reset(self) -> None: ...
    def __enter__(self) -> Tokenizer: ...
    def __exit__(self, *exc: object) -> None: ...
    def __iter__(self) -> Iterator[Token]: ...

def tokenize(
    s: str,
    /,
    *,
    resolve_references: bool = ...,
    capture_source: bool = ...,
    capture_attributes: bool = ...,
) -> Iterator[Token]: ...

@final
class _RewriteHandle:
    @property
    def kind(self) -> str: ...
    @property
    def removed(self) -> bool: ...
    @property
    def tag(self) -> str: ...
    @property
    def attrs(self) -> tuple[tuple[str, str | None], ...]: ...
    @property
    def text(self) -> str: ...
    @property
    def name(self) -> str | None: ...
    @property
    def public_id(self) -> str | None: ...
    @property
    def system_id(self) -> str | None: ...
    def before(self, content: str, *, html: bool = ...) -> None: ...
    def after(self, content: str, *, html: bool = ...) -> None: ...
    def replace(self, content: str, *, html: bool = ...) -> None: ...
    def remove(self) -> None: ...
    def set_content(self, content: str, *, html: bool = ...) -> None: ...
    def append(self, content: str, *, html: bool = ...) -> None: ...
    def prepend(self, content: str, *, html: bool = ...) -> None: ...
    def remove_and_keep_content(self) -> None: ...
    def get(self, name: str, default: str | None = ..., /) -> str | None: ...
    def has_attribute(self, name: str, /) -> bool: ...
    def set_attribute(self, name: str, value: str, /) -> None: ...
    def remove_attribute(self, name: str, /) -> None: ...
    def set_text(self, value: str, /) -> None: ...

def _rewrite(
    source: str,
    element_handlers: tuple[tuple[str, object], ...],
    text_handler: object,
    comment_handler: object,
    doctype_handler: object,
    /,
) -> str: ...
def _sax_events(html: str, /) -> Iterator[tuple[object, ...]]: ...
def _tokenize_states(
    text: str, initial_state: str, last_start_tag: str | None = ..., storage_kind: int = ..., /
) -> tuple[list[tuple[object, ...]], list[tuple[str, int, int]]]: ...
def _grow_probe(needed: int, current: int, initial: int, elem_size: int, /) -> tuple[int, int, int]: ...
