# Subsystem: validate (_c/validate) — XSD and RELAX NG schema validation.
from .dom import Node

def _schema_compile(kind: int, source: str, /) -> object: ...
def _schema_validate(schema: object, node: Node, /) -> tuple[bool, list[tuple[str, str, int, str]]]: ...
