# Subsystem: validate (_c/validate) — XSD/RELAX NG schema validation and HTML5 conformance.
from turbohtml.conformance import ConformanceMessage

from .dom import Node

def _schema_compile(kind: int, source: str, /) -> object: ...
def _schema_validate(schema: object, node: Node, /) -> tuple[bool, list[tuple[str, str, int, str]]]: ...
def _conformance_check(node: Node, /) -> tuple[bool, list[tuple[str, str, str, int, int]]]: ...
def _conformance_filter(
    messages: tuple[ConformanceMessage, ...], severity: str, /
) -> tuple[ConformanceMessage, ...]: ...
