import re
from collections.abc import Callable, Iterable, Iterator, Mapping, MutableMapping, Sequence
from enum import Enum, IntEnum
from typing import TypeAlias, final

_Filter: TypeAlias = str | re.Pattern[str] | bool | Callable[[str | None], bool] | list[_Filter]

class Axis(IntEnum):
    DESCENDANTS = 0
    CHILDREN = 1
    ANCESTORS = 2
    NEXT_SIBLINGS = 3
    PREVIOUS_SIBLINGS = 4
    FOLLOWING = 5
    PRECEDING = 6

def escape(s: str, quote: bool = ...) -> str: ...
def unescape(s: str, /) -> str: ...
def _markup_escape(s: object, /) -> str: ...
def _markup_escape_silent(s: object, /) -> str: ...
def _markup_soft_str(s: object, /) -> str: ...
def _register_markup(markup_type: type, /) -> None: ...
def _linkify_scan(text: str, parse_email: bool, bare_domains: bool, /) -> list[tuple[int, int, int]]: ...

class TokenType(IntEnum):
    TEXT = 0
    START_TAG = 1
    END_TAG = 2
    COMMENT = 3
    DOCTYPE = 4

@final
class Token:
    @property
    def type(self) -> TokenType: ...
    @property
    def data(self) -> str | None: ...
    @property
    def tag(self) -> str | None: ...
    @property
    def attrs(self) -> list[tuple[str, str | None]] | None: ...
    @property
    def self_closing(self) -> bool: ...
    @property
    def name(self) -> str | None: ...
    @property
    def public_id(self) -> str | None: ...
    @property
    def system_id(self) -> str | None: ...
    @property
    def force_quirks(self) -> bool: ...
    @property
    def line(self) -> int: ...
    @property
    def col(self) -> int: ...
    def attr(self, name: str, default: str | None = None) -> str | None: ...

@final
class Tokenizer:
    def __init__(self) -> None: ...
    def feed(self, data: str) -> Iterator[Token]: ...
    def close(self) -> Iterator[Token]: ...
    def reset(self) -> None: ...
    def __enter__(self) -> Tokenizer: ...
    def __exit__(self, *exc: object) -> None: ...
    def __iter__(self) -> Iterator[Token]: ...

def tokenize(s: str, /) -> Iterator[Token]: ...
def _tokenize_states(
    text: str, initial_state: str, last_start_tag: str | None = ..., storage_kind: int = ..., /
) -> list[tuple[object, ...]]: ...

class Namespace(Enum):
    HTML = "html"
    SVG = "svg"
    MATHML = "math"

class Formatter(Enum):
    WHATWG = "whatwg"
    MINIMAL = "minimal"
    NAMED_ENTITIES = "named"

class Node:
    @property
    def parent(self) -> Element | Document | None: ...
    @property
    def children(self) -> Sequence[Node]: ...
    @property
    def next_sibling(self) -> Node | None: ...
    @property
    def previous_sibling(self) -> Node | None: ...
    @property
    def descendants(self) -> Iterator[Node]: ...
    @property
    def ancestors(self) -> Iterator[Element | Document]: ...
    @property
    def next_siblings(self) -> Iterator[Node]: ...
    @property
    def previous_siblings(self) -> Iterator[Node]: ...
    @property
    def following(self) -> Iterator[Node]: ...
    @property
    def preceding(self) -> Iterator[Node]: ...
    @property
    def strings(self) -> Iterator[str]: ...
    @property
    def stripped_strings(self) -> Iterator[str]: ...
    @property
    def text(self) -> str: ...
    @property
    def html(self) -> str: ...
    @property
    def inner_html(self) -> str: ...
    def find(
        self,
        tag: _Filter | None = None,
        /,
        *,
        axis: Axis = ...,
        attrs: Mapping[str, _Filter] | None = ...,
        class_: _Filter | None = ...,
        **filters: _Filter,
    ) -> Element | None: ...
    def find_all(
        self,
        tag: _Filter | None = None,
        /,
        *,
        axis: Axis = ...,
        attrs: Mapping[str, _Filter] | None = ...,
        class_: _Filter | None = ...,
        limit: int | None = ...,
        **filters: _Filter,
    ) -> list[Element]: ...
    def select(self, selector: str, /) -> list[Element]: ...
    def select_one(self, selector: str, /) -> Element | None: ...
    def matches(self, selector: str, /) -> bool: ...
    def closest(self, selector: str, /) -> Element | None: ...
    def serialize(self, *, formatter: Formatter = ..., indent: int | str | None = ...) -> str: ...
    def encode(
        self, encoding: str = "utf-8", *, formatter: Formatter = ..., indent: int | str | None = ...
    ) -> bytes: ...
    def insert_before(self, *nodes: Node) -> None: ...
    def insert_after(self, *nodes: Node) -> None: ...
    def replace_with(self, *nodes: Node) -> None: ...
    def wrap(self, wrapper: Element, /) -> Element: ...
    def unwrap(self) -> Node: ...
    def extract(self) -> Node: ...
    def decompose(self) -> None: ...
    def __iter__(self) -> Iterator[Node]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Node: ...
    def __bool__(self) -> bool: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

@final
class Element(Node):
    __match_args__ = ("tag",)
    def __init__(self, tag: str, attrs: Mapping[str, str | list[str] | None] | None = None) -> None: ...
    @property
    def tag(self) -> str: ...
    @property
    def namespace(self) -> Namespace: ...
    @property
    def attrs(self) -> MutableMapping[str, str | list[str] | None]: ...
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
    def append(self, child: Node, /) -> None: ...
    def extend(self, children: Iterable[Node], /) -> None: ...
    def insert(self, index: int, child: Node, /) -> None: ...
    def clear(self) -> None: ...
    def normalize(self) -> None: ...

@final
class Text(Node):
    __match_args__ = ("data",)
    def __init__(self, data: str) -> None: ...
    @property
    def data(self) -> str: ...
    @data.setter
    def data(self, value: str) -> None: ...

@final
class Comment(Node):
    __match_args__ = ("data",)
    def __init__(self, data: str) -> None: ...
    @property
    def data(self) -> str: ...
    @data.setter
    def data(self, value: str) -> None: ...

@final
class CData(Node):
    __match_args__ = ("data",)
    def __init__(self, data: str) -> None: ...
    @property
    def data(self) -> str: ...
    @data.setter
    def data(self, value: str) -> None: ...

@final
class ProcessingInstruction(Node):
    __match_args__ = ("target", "data")
    def __init__(self, target: str, data: str) -> None: ...
    @property
    def target(self) -> str: ...
    @property
    def data(self) -> str: ...

@final
class Doctype(Node):
    __match_args__ = ("name",)
    @property
    def name(self) -> str: ...
    @property
    def public_id(self) -> str | None: ...
    @property
    def system_id(self) -> str | None: ...

@final
class Document(Node):
    __match_args__ = ("root",)
    @property
    def root(self) -> Element | None: ...
    @property
    def encoding(self) -> str | None: ...

def parse(markup: str | bytes, *, encoding: str | None = None) -> Document: ...
def parse_fragment(html: str, context: str = "div") -> Element: ...
def _parse_tree(html: str, /) -> str: ...
def _parse_fragment(html: str, context: str, /) -> str: ...
def _parse_only(html: str, /) -> None: ...
