"""
Generate src/turbohtml/_c/data/tld_table.h from IANA's list of top-level domains.

linkify recognizes a bare domain like ``example.com`` as a link only when its last label is a real TLD, the same
rule bleach used. The canonical list is IANA's, so this downloads it, lowercases and sorts every entry (including the
``xn--`` punycode TLDs, so a real ``xn--p1ai`` matches while a made-up ``xn--whatever`` does not), and emits a
generated header shaped like ``tag_atom.h``: a sorted ``{name, len}`` array plus a 256-entry first-byte index, so a
label is matched by bucketing on its first byte and a case-insensitive ``memcmp``. IANA serves only the current list,
so the expected ``IANA_VERSION`` is pinned and a rebuild refuses a silent drift; the version is also recorded in the
header so a deliberate bump shows an auditable diff.

Usage:  python tools/generate_tlds.py src/turbohtml/_c/data/tld_table.h
"""

from __future__ import annotations

import sys
import urllib.request
from pathlib import Path

IANA_TLDS_URL = "https://data.iana.org/TLD/tlds-alpha-by-domain.txt"

# IANA publishes only the latest list at a stable URL, so a rebuild can never fetch a past version -- the committed
# table would drift with whatever IANA serves that day. Pin the expected version and fail a rebuild that sees a
# different one; bump IANA_VERSION deliberately and review the tld_table.h diff. Matches the committed table.
IANA_VERSION = "Version 2026061600"


def fetch_tlds() -> tuple[str, list[str]]:
    """Return the pinned IANA version and the lowercased ASCII TLDs, punycode entries included."""
    with urllib.request.urlopen(IANA_TLDS_URL) as response:
        text = response.read().decode("ascii")
    version = ""
    names: list[str] = []
    for line in text.splitlines():
        if line.startswith("#"):
            if "Version" in line:  # "# Version 2026061600, Last Updated ..."; keep just the version number
                version = line.lstrip("# ").split(",", 1)[0].strip()
            continue
        if name := line.strip().lower():
            names.append(name)
    if version != IANA_VERSION:
        msg = f"IANA served {version!r}, expected the pinned {IANA_VERSION!r}; bump IANA_VERSION to regenerate"
        raise SystemExit(msg)
    return version, sorted(names)


def generate(out_path: Path) -> None:
    """Write the generated TLD-table C header to *out_path*."""
    version, names = fetch_tlds()
    table_lines = "\n".join(f'    {{"{name}", {len(name)}u}},' for name in names)

    # Names are sorted, so entries sharing a first byte are contiguous; first_index[b] holds the offset of the first
    # entry whose name starts with a byte >= b, so the bucket for byte b is [first_index[b], first_index[b + 1]).
    first_index = [len(names)] * 257
    for index, name in enumerate(names):
        first_byte = ord(name[0])
        first_index[first_byte] = min(first_index[first_byte], index)
    running = len(names)
    for byte_value in range(256, -1, -1):
        running = min(running, first_index[byte_value])
        first_index[byte_value] = running
    index_rows = ", ".join(str(first_index[byte_value]) for byte_value in range(257))

    out_path.write_text(
        "/* Auto-generated by tools/generate_tlds.py - do not edit. */\n"
        f"/* IANA top-level domains ({version}), including the xn-- punycode TLDs. */\n\n"
        "#ifndef TURBOHTML_TLD_TABLE_H\n"
        "#define TURBOHTML_TLD_TABLE_H\n\n"
        "#include <stdint.h>\n\n"
        "typedef struct {\n"
        "    const char *name;\n"
        "    uint8_t name_len;\n"
        "} th_tld_entry;\n\n"
        f"static const int th_tld_count = {len(names)};\n"
        "static const th_tld_entry th_tld_table[] = {\n"
        f"{table_lines}\n"
        "};\n\n"
        "/* th_tld_first[c] is the first table index whose name starts with a byte >= c, so the entries\n"
        "   beginning with byte c are [th_tld_first[c], th_tld_first[c + 1]). */\n"
        "static const uint16_t th_tld_first[257] = {\n"
        f"    {index_rows}\n"
        "};\n\n"
        "#endif /* TURBOHTML_TLD_TABLE_H */\n",
        encoding="utf-8",
    )
    print(f"wrote {out_path}: {len(names)} TLDs ({version})")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        msg = "usage: generate_tlds.py OUTPUT_HEADER"
        raise SystemExit(msg)
    generate(Path(sys.argv[1]))
