"""
Generate src/turbohtml/_c/data/psl_table.h from the Public Suffix List.

The registrable-domain boundary behind :func:`turbohtml.extract.extract_links`'s ``external_only`` needs the multi-label
public suffixes (``co.uk``, ``github.io``, the ``*.ck`` wildcards) that the single-label IANA table cannot express: a
label such as ``co`` or ``tv`` is itself a delegated TLD, so a plain "trailing TLD labels" rule would wrongly fold
``sub.tv.com`` into ``tv.com``. The canonical source of the multi-label rules is the Public Suffix List, so this
downloads it, keeps only the rules with at least two labels (the single-label public suffixes are the IANA TLDs already
in ``tld_table.h``), punycodes any Unicode labels so they match the ASCII hosts ``normalize_url`` emits, and writes a
generated header shaped like ``tld_table.h``: a sorted ``{name, len, labels, kind}`` array plus a 256-entry first-byte
index, so a candidate suffix is matched by bucketing on its first byte and a case-insensitive ``memcmp``.

A rule's ``kind`` is 0 for a normal rule (``co.uk``), 1 for a wildcard rule stored with its ``*.`` prefix (``*.ck``,
matching any single label in that position), and 2 for an exception rule stored without its leading ``!`` (``www.ck``,
which narrows the wildcard it sits under). The list is fetched at the pinned ``PSL_COMMIT`` rather than off ``main``,
so a rebuild is deterministic and the header records the exact commit for an auditable diff.

Usage:  python tools/generate_psl.py src/turbohtml/_c/data/psl_table.h
"""

from __future__ import annotations

import sys
import urllib.request
from pathlib import Path

# The Public Suffix List ships no releases, so a rebuild off @main would silently drift with whatever the branch
# points at that day -- a reproducibility and supply-chain gap. Pin a specific commit instead; bump it deliberately
# and review the psl_table.h diff. Pinned to the publicsuffix/list main tip of 2026-07-01.
PSL_COMMIT = "d67b6cb8e70e9c76b0803809b66e7ffdd09484bd"
PSL_URL = f"https://raw.githubusercontent.com/publicsuffix/list/{PSL_COMMIT}/public_suffix_list.dat"

_NORMAL = 0
_WILDCARD = 1
_EXCEPTION = 2


def _punycode(rule: str) -> str:
    """Return *rule* with every non-ASCII label converted to its ``xn--`` form, leaving ``*`` and ASCII untouched."""
    return ".".join(
        label if label == "*" or label.isascii() else label.encode("idna").decode("ascii") for label in rule.split(".")
    )


def fetch_rules() -> tuple[str, list[tuple[str, int]]]:
    """Return the fetched-commit marker and the ``(rule_text, kind)`` pairs for every multi-label PSL rule."""
    with urllib.request.urlopen(PSL_URL) as response:
        text = response.read().decode("utf-8")
    rules: dict[str, int] = {}
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("//"):
            continue
        kind = _EXCEPTION if line.startswith("!") else (_WILDCARD if line.startswith("*.") else _NORMAL)
        rule = _punycode(line.removeprefix("!").lower())
        if rule.count(".") >= 1:  # single-label public suffixes are the IANA TLDs in tld_table.h
            rules[rule] = kind
    return PSL_COMMIT, sorted(rules.items())


def generate(out_path: Path) -> None:
    """Write the generated public-suffix-table C header to *out_path*."""
    commit, pairs = fetch_rules()
    names = [name for name, _kind in pairs]
    table_lines = "\n".join(f'    {{"{name}", {len(name)}u, {name.count(".") + 1}u, {kind}u}},' for name, kind in pairs)

    # Names are sorted, so entries sharing a first byte are contiguous; first_index[b] holds the offset of the first
    # entry whose name starts with a byte >= b, so the bucket for byte b is [first_index[b], first_index[b + 1]).
    first_index = [len(names)] * 257
    for index, name in enumerate(names):
        first_byte = ord(name[0])
        first_index[first_byte] = min(first_index[first_byte], index)
    running = len(names)
    for byte_value in range(256, -1, -1):
        running = min(running, first_index[byte_value])
        first_index[byte_value] = running
    index_rows = ", ".join(str(first_index[byte_value]) for byte_value in range(257))

    out_path.write_text(
        "/* Auto-generated by tools/generate_psl.py - do not edit. */\n"
        f"/* Public Suffix List multi-label rules (publicsuffix/list@{commit}), Unicode labels punycoded. */\n\n"
        "#ifndef TURBOHTML_PSL_TABLE_H\n"
        "#define TURBOHTML_PSL_TABLE_H\n\n"
        "#include <stdint.h>\n\n"
        "/* kind: 0 normal (co.uk), 1 wildcard with its *. prefix (*.ck), 2 exception without its ! (www.ck). */\n"
        "typedef struct {\n"
        "    const char *name;\n"
        "    uint8_t name_len;\n"
        "    uint8_t labels;\n"
        "    uint8_t kind;\n"
        "} th_psl_entry;\n\n"
        f"static const int th_psl_count = {len(names)};\n"
        "static const th_psl_entry th_psl_table[] = {\n"
        f"{table_lines}\n"
        "};\n\n"
        "/* th_psl_first[c] is the first table index whose name starts with a byte >= c, so the entries\n"
        "   beginning with byte c are [th_psl_first[c], th_psl_first[c + 1]). */\n"
        "static const uint16_t th_psl_first[257] = {\n"
        f"    {index_rows}\n"
        "};\n\n"
        "#endif /* TURBOHTML_PSL_TABLE_H */\n",
        encoding="utf-8",
    )
    print(f"wrote {out_path}: {len(names)} rules (publicsuffix/list@{commit})")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        msg = "usage: generate_psl.py OUTPUT_HEADER"
        raise SystemExit(msg)
    generate(Path(sys.argv[1]))
