"""
Generate src/turbohtml/html_entities.h from the HTML5 specification data.

The C accelerator binary-searches the HTML5 named-reference table and the
numeric-charref correction tables. The named table comes from the public
:data:`html.entities.html5` mapping; the numeric correction tables are built here
directly from the `WHATWG HTML specification
<https://html.spec.whatwg.org/multipage/parsing.html#numeric-character-reference-end-state>`_
so we do not depend on any private standard-library internals.

Usage:  python tools/generate_html_entities.py src/turbohtml/html_entities.h
"""

from __future__ import annotations

import sys
from html.entities import html5
from pathlib import Path


def _windows_1252(codepoint: int) -> str:
    """Return the Windows-1252 character for a C1 control byte, else the byte itself."""
    try:
        return bytes([codepoint]).decode("cp1252")
    except UnicodeDecodeError:  # the five undefined cp1252 slots pass through unchanged
        return chr(codepoint)


# Numeric character references in the C1 range are reinterpreted as Windows-1252,
# with U+0000 and a bare CR getting their own replacements (HTML spec table).
_invalid_charrefs = {0x00: "\ufffd", 0x0D: "\r", **{cp: _windows_1252(cp) for cp in range(0x80, 0xA0)}}
# Code points that the spec forbids in numeric references: C0/C1 controls (minus
# the allowed whitespace), the Arabic-block noncharacters, and the per-plane ones.
_invalid_codepoints = (
    set(range(0x01, 0x09))
    | {0x0B}
    | set(range(0x0E, 0x20))
    | set(range(0x7F, 0xA0))
    | set(range(0xFDD0, 0xFDF0))
    | {(plane << 16) + low for plane in range(0x11) for low in (0xFFFE, 0xFFFF)}
)


def generate(out_path: Path) -> None:
    """Write the generated HTML5 entity-table C header to *out_path*."""
    if (longest := max(len(value) for value in html5.values())) > 2:  # a named ref expands to at most two code points
        msg = f"named value longer than 2 code points: {longest}"
        raise SystemExit(msg)
    max_name_len = max(len(name) for name in html5)

    ordered = sorted(html5)
    named = [
        f'    {{"{name}", {len(name)}u, {ord(value[0])}u, {ord(value[1]) if len(value) == 2 else 0}u}},'
        for name in ordered
        for value in (html5[name],)
    ]
    # the names html.escape emits dominate real input; expose their indices so
    # unescape can check them with one comparison before the binary search
    escape_defines = "".join(
        f"#define HTML5_INDEX_{name.rstrip(';').upper()} {ordered.index(name)}\n"
        for name in ("amp;", "apos;", "gt;", "lt;", "quot;")
    )
    charrefs = [f"    {{{num}u, {ord(_invalid_charrefs[num])}u}}," for num in sorted(_invalid_charrefs)]
    codepoints = sorted(_invalid_codepoints)
    codepoint_lines = "\n".join(
        "    " + " ".join(f"{codepoint}u," for codepoint in codepoints[start : start + 10])
        for start in range(0, len(codepoints), 10)
    )

    out_path.write_text(
        "/* Auto-generated by tools/generate_html_entities.py - do not edit. */\n"
        "/* HTML5 named references and numeric-charref correction tables. */\n\n"
        "typedef struct {\n"
        "    const char *name;\n"
        "    unsigned char name_len;\n"
        "    Py_UCS4 cp0;\n"
        "    Py_UCS4 cp1; /* second code point, or 0 when the value is one char */\n"
        "} html5_entity;\n\n"
        f"#define HTML5_MAX_NAME_LEN {max_name_len}\n"
        f"{escape_defines}"
        f"static const int html5_count = {len(named)};\n"
        "static const html5_entity html5_entities[] = {\n"
        f"{chr(10).join(named)}\n"
        "};\n\n"
        "typedef struct { Py_UCS4 num; Py_UCS4 cp; } html5_charref;\n"
        f"static const int invalid_charref_count = {len(charrefs)};\n"
        "static const html5_charref invalid_charrefs[] = {\n"
        f"{chr(10).join(charrefs)}\n"
        "};\n\n"
        f"static const int invalid_codepoint_count = {len(codepoints)};\n"
        "static const Py_UCS4 invalid_codepoints[] = {\n"
        f"{codepoint_lines}\n"
        "};\n",
        encoding="utf-8",
    )
    print(f"wrote {out_path}: {len(named)} named, {len(charrefs)} charrefs, {len(codepoints)} codepoints")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    generate(Path(sys.argv[1]))
